### ISSUE TITLE
Missed vanilla traits associated with Bard building

### ISSUE THREAD

**Issue by DrunkFlamingo** [Shieldwall-TOB/Shieldwall-Script-Library#111]
Trait key unknown. Reporter had terrible english. 

Likely reproduction start game as Gwined sit in capital settlement with bard and wait for the chance to trigger. He said it was on second turn so likely a high chance

**Comment by AmericanCaesar** [comment]
Quote is "definitely the Traits are not working good with Bard (Dublin). The Mind nad Body are geting bad traits without sense in the second turn. Check it please when you have time for it"

**Comment by AmericanCaesar** [comment]
I just did 60 turns of just waiting around in Dyflin as Bardr and didn't come across anything. I know the user who reported this often doesn't play in English which causes all sorts of issues. I haven't heard any complaints about it since so I'm going to close this. Feel free to reopen if you think it requires further investigation.
